[snowflake]
host = "mlebwsc-gy11780.snowflakecomputing.com"
database = "CORTEX_ANALYST_DEMO"
schema = "SALESMETRICSMODEL_SCHEMA"
stage = "RAW_DATA"
file = "SalesMetricsModel.yml"
user = "Ashik"
password = "12345qwert$%Q"
account = "mlebwsc-gy11780"
warehouse = "COMPUTE_WH"
role = "SYSADMIN"
